export interface NaiveComponentEntry {
  name: string
  export: string
  dir: string
}

export const naiveComponents: NaiveComponentEntry[] = [
  { name: 'NAffix', export: 'NAffix', dir: 'affix' },
  { name: 'NAlert', export: 'NAlert', dir: 'alert' },
  { name: 'NAnchor', export: 'NAnchor', dir: 'anchor' },
  { name: 'NAnchorLink', export: 'NAnchorLink', dir: 'anchor' },
  { name: 'NAutoComplete', export: 'NAutoComplete', dir: 'auto-complete' },
  { name: 'NAvatar', export: 'NAvatar', dir: 'avatar' },
  { name: 'NAvatarGroup', export: 'NAvatarGroup', dir: 'avatar-group' },
  { name: 'NBackTop', export: 'NBackTop', dir: 'back-top' },
  { name: 'NBadge', export: 'NBadge', dir: 'badge' },
  { name: 'NBreadcrumb', export: 'NBreadcrumb', dir: 'breadcrumb' },
  { name: 'NBreadcrumbItem', export: 'NBreadcrumbItem', dir: 'breadcrumb' },
  { name: 'NButton', export: 'NButton', dir: 'button' },
  { name: 'NButtonGroup', export: 'NButtonGroup', dir: 'button-group' },
  { name: 'NCalendar', export: 'NCalendar', dir: 'calendar' },
  { name: 'NCard', export: 'NCard', dir: 'card' },
  { name: 'NCarousel', export: 'NCarousel', dir: 'carousel' },
  { name: 'NCarouselItem', export: 'NCarouselItem', dir: 'carousel' },
  { name: 'NCascader', export: 'NCascader', dir: 'cascader' },
  { name: 'NCheckbox', export: 'NCheckbox', dir: 'checkbox' },
  { name: 'NCheckboxGroup', export: 'NCheckboxGroup', dir: 'checkbox' },
  { name: 'NCode', export: 'NCode', dir: 'code' },
  { name: 'NCollapse', export: 'NCollapse', dir: 'collapse' },
  { name: 'NCollapseItem', export: 'NCollapseItem', dir: 'collapse' },
  {
    name: 'NCollapseTransition',
    export: 'NCollapseTransition',
    dir: 'collapse-transition'
  },
  { name: 'NColorPicker', export: 'NColorPicker', dir: 'color-picker' },
  {
    name: 'NConfigProvider',
    export: 'NConfigProvider',
    dir: 'config-provider'
  },
  { name: 'NCountdown', export: 'NCountdown', dir: 'countdown' },
  { name: 'NDataTable', export: 'NDataTable', dir: 'data-table' },
  { name: 'NDatePicker', export: 'NDatePicker', dir: 'date-picker' },
  { name: 'NDescriptions', export: 'NDescriptions', dir: 'descriptions' },
  {
    name: 'NDescriptionsItem',
    export: 'NDescriptionsItem',
    dir: 'descriptions'
  },
  { name: 'NDialog', export: 'NDialog', dir: 'dialog' },
  { name: 'NDialogProvider', export: 'NDialogProvider', dir: 'dialog' },
  { name: 'NDivider', export: 'NDivider', dir: 'divider' },
  { name: 'NDrawer', export: 'NDrawer', dir: 'drawer' },
  { name: 'NDrawerContent', export: 'NDrawerContent', dir: 'drawer' },
  { name: 'NDropdown', export: 'NDropdown', dir: 'dropdown' },
  { name: 'NDynamicInput', export: 'NDynamicInput', dir: 'dynamic-input' },
  { name: 'NDynamicTags', export: 'NDynamicTags', dir: 'dynamic-tags' },
  { name: 'NEl', export: 'NEl', dir: 'element' },
  { name: 'NElement', export: 'NElement', dir: 'element' },
  { name: 'NEllipsis', export: 'NEllipsis', dir: 'ellipsis' },
  {
    name: 'NPerformantEllipsis',
    export: 'NPerformantEllipsis',
    dir: 'ellipsis'
  },
  { name: 'NEmpty', export: 'NEmpty', dir: 'empty' },
  { name: 'NEquation', export: 'NEquation', dir: 'equation' },
  { name: 'NFlex', export: 'NFlex', dir: 'flex' },
  { name: 'NFloatButton', export: 'NFloatButton', dir: 'float-button' },
  {
    name: 'NFloatButtonGroup',
    export: 'NFloatButtonGroup',
    dir: 'float-button-group'
  },
  { name: 'NForm', export: 'NForm', dir: 'form' },
  { name: 'NFormItem', export: 'NFormItem', dir: 'form' },
  { name: 'NFormItemCol', export: 'NFormItemCol', dir: 'form' },
  { name: 'NFormItemGi', export: 'NFormItemGi', dir: 'form' },
  { name: 'NFormItemGridItem', export: 'NFormItemGridItem', dir: 'form' },
  { name: 'NFormItemRow', export: 'NFormItemRow', dir: 'form' },
  { name: 'NGlobalStyle', export: 'NGlobalStyle', dir: 'global-style' },
  { name: 'NGradientText', export: 'NGradientText', dir: 'gradient-text' },
  { name: 'NGi', export: 'NGi', dir: 'grid' },
  { name: 'NGrid', export: 'NGrid', dir: 'grid' },
  { name: 'NGridItem', export: 'NGridItem', dir: 'grid' },
  { name: 'NHeatmap', export: 'NHeatmap', dir: 'heatmap' },
  { name: 'NHighlight', export: 'NHighlight', dir: 'highlight' },
  { name: 'NIcon', export: 'NIcon', dir: 'icon' },
  { name: 'NIconWrapper', export: 'NIconWrapper', dir: 'icon-wrapper' },
  { name: 'NImage', export: 'NImage', dir: 'image' },
  { name: 'NImageGroup', export: 'NImageGroup', dir: 'image' },
  { name: 'NImagePreview', export: 'NImagePreview', dir: 'image' },
  {
    name: 'NInfiniteScroll',
    export: 'NInfiniteScroll',
    dir: 'infinite-scroll'
  },
  { name: 'NInput', export: 'NInput', dir: 'input' },
  { name: 'NInputGroup', export: 'NInputGroup', dir: 'input' },
  { name: 'NInputGroupLabel', export: 'NInputGroupLabel', dir: 'input' },
  { name: 'NInputNumber', export: 'NInputNumber', dir: 'input-number' },
  { name: 'NInputOtp', export: 'NInputOtp', dir: 'input-otp' },
  { name: 'NLayout', export: 'NLayout', dir: 'layout' },
  { name: 'NLayoutContent', export: 'NLayoutContent', dir: 'layout' },
  { name: 'NLayoutFooter', export: 'NLayoutFooter', dir: 'layout' },
  { name: 'NLayoutHeader', export: 'NLayoutHeader', dir: 'layout' },
  { name: 'NLayoutSider', export: 'NLayoutSider', dir: 'layout' },
  { name: 'NCol', export: 'NCol', dir: 'legacy-grid' },
  { name: 'NRow', export: 'NRow', dir: 'legacy-grid' },
  {
    name: 'NLegacyTransfer',
    export: 'NLegacyTransfer',
    dir: 'legacy-transfer'
  },
  { name: 'NList', export: 'NList', dir: 'list' },
  { name: 'NListItem', export: 'NListItem', dir: 'list' },
  {
    name: 'NLoadingBarProvider',
    export: 'NLoadingBarProvider',
    dir: 'loading-bar'
  },
  { name: 'NLog', export: 'NLog', dir: 'log' },
  { name: 'NMarquee', export: 'NMarquee', dir: 'marquee' },
  { name: 'NMention', export: 'NMention', dir: 'mention' },
  { name: 'NMenu', export: 'NMenu', dir: 'menu' },
  { name: 'NMessageProvider', export: 'NMessageProvider', dir: 'message' },
  { name: 'NModal', export: 'NModal', dir: 'modal' },
  { name: 'NModalProvider', export: 'NModalProvider', dir: 'modal' },
  {
    name: 'NNotificationProvider',
    export: 'NNotificationProvider',
    dir: 'notification'
  },
  {
    name: 'NNumberAnimation',
    export: 'NNumberAnimation',
    dir: 'number-animation'
  },
  { name: 'NPageHeader', export: 'NPageHeader', dir: 'page-header' },
  { name: 'NPagination', export: 'NPagination', dir: 'pagination' },
  { name: 'NPopconfirm', export: 'NPopconfirm', dir: 'popconfirm' },
  { name: 'NPopover', export: 'NPopover', dir: 'popover' },
  { name: 'NPopselect', export: 'NPopselect', dir: 'popselect' },
  { name: 'NProgress', export: 'NProgress', dir: 'progress' },
  { name: 'NQrCode', export: 'NQrCode', dir: 'qr-code' },
  { name: 'NRadio', export: 'NRadio', dir: 'radio' },
  { name: 'NRadioButton', export: 'NRadioButton', dir: 'radio' },
  { name: 'NRadioGroup', export: 'NRadioGroup', dir: 'radio' },
  { name: 'NRate', export: 'NRate', dir: 'rate' },
  { name: 'NResult', export: 'NResult', dir: 'result' },
  { name: 'NScrollbar', export: 'NScrollbar', dir: 'scrollbar' },
  { name: 'NSelect', export: 'NSelect', dir: 'select' },
  { name: 'NSkeleton', export: 'NSkeleton', dir: 'skeleton' },
  { name: 'NSlider', export: 'NSlider', dir: 'slider' },
  { name: 'NSpace', export: 'NSpace', dir: 'space' },
  { name: 'NSpin', export: 'NSpin', dir: 'spin' },
  { name: 'NSplit', export: 'NSplit', dir: 'split' },
  { name: 'NStatistic', export: 'NStatistic', dir: 'statistic' },
  { name: 'NStep', export: 'NStep', dir: 'steps' },
  { name: 'NSteps', export: 'NSteps', dir: 'steps' },
  { name: 'NSwitch', export: 'NSwitch', dir: 'switch' },
  { name: 'NTable', export: 'NTable', dir: 'table' },
  { name: 'NTbody', export: 'NTbody', dir: 'table' },
  { name: 'NTd', export: 'NTd', dir: 'table' },
  { name: 'NTh', export: 'NTh', dir: 'table' },
  { name: 'NThead', export: 'NThead', dir: 'table' },
  { name: 'NTr', export: 'NTr', dir: 'table' },
  { name: 'NTab', export: 'NTab', dir: 'tabs' },
  { name: 'NTabPane', export: 'NTabPane', dir: 'tabs' },
  { name: 'NTabs', export: 'NTabs', dir: 'tabs' },
  { name: 'NTag', export: 'NTag', dir: 'tag' },
  { name: 'NThing', export: 'NThing', dir: 'thing' },
  { name: 'NTime', export: 'NTime', dir: 'time' },
  { name: 'NTimePicker', export: 'NTimePicker', dir: 'time-picker' },
  { name: 'NTimeline', export: 'NTimeline', dir: 'timeline' },
  { name: 'NTimelineItem', export: 'NTimelineItem', dir: 'timeline' },
  { name: 'NTooltip', export: 'NTooltip', dir: 'tooltip' },
  { name: 'NTransfer', export: 'NTransfer', dir: 'transfer' },
  { name: 'NTree', export: 'NTree', dir: 'tree' },
  { name: 'NTreeSelect', export: 'NTreeSelect', dir: 'tree-select' },
  { name: 'NA', export: 'NA', dir: 'typography' },
  { name: 'NBlockquote', export: 'NBlockquote', dir: 'typography' },
  { name: 'NH1', export: 'NH1', dir: 'typography' },
  { name: 'NH2', export: 'NH2', dir: 'typography' },
  { name: 'NH3', export: 'NH3', dir: 'typography' },
  { name: 'NH4', export: 'NH4', dir: 'typography' },
  { name: 'NH5', export: 'NH5', dir: 'typography' },
  { name: 'NH6', export: 'NH6', dir: 'typography' },
  { name: 'NHr', export: 'NHr', dir: 'typography' },
  { name: 'NLi', export: 'NLi', dir: 'typography' },
  { name: 'NOl', export: 'NOl', dir: 'typography' },
  { name: 'NP', export: 'NP', dir: 'typography' },
  { name: 'NText', export: 'NText', dir: 'typography' },
  { name: 'NUl', export: 'NUl', dir: 'typography' },
  { name: 'NUpload', export: 'NUpload', dir: 'upload' },
  { name: 'NUploadDragger', export: 'NUploadDragger', dir: 'upload' },
  { name: 'NUploadFileList', export: 'NUploadFileList', dir: 'upload' },
  { name: 'NUploadTrigger', export: 'NUploadTrigger', dir: 'upload' },
  { name: 'NVirtualList', export: 'NVirtualList', dir: 'virtual-list' },
  { name: 'NWatermark', export: 'NWatermark', dir: 'watermark' }
]
